// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIFiles.
// Make any needed changes in class CreateUIFiles.

// Define binding names for C# to UI.
export class uiBindingNames
{
    public static SelectedDistrict                     : string = "SelectedDistrict";
    public static DistrictInfos                        : string = "DistrictInfos";
    public static DisplayOption                        : string = "DisplayOption";
    public static ColorOption                          : string = "ColorOption";
    public static OneColor                             : string = "OneColor";
    public static ResourceInfos                        : string = "ResourceInfos";
}

// Define event names for UI to C#.
export class uiEventNames
{
    public static SelectedDistrictChanged              : string = "SelectedDistrictChanged";
    public static DisplayOptionClicked                 : string = "DisplayOptionClicked";
    public static ColorOptionClicked                   : string = "ColorOptionClicked";
    public static OneColorChanged                      : string = "OneColorChanged";
}
