// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIFiles.
// Make any needed changes in class CreateUIFiles.


// Define building types.
export enum RLBuildingType
{
    None                             = 246800,
    District                         = 246801,
    DisplayOption                    = 246802,
    ColorOption                      = 246803,
    SelectDeselect                   = 246804,
    HeadingMaterials                 = 246805,
    Wood                             = 246806,
    Grain                            = 246807,
    Livestock                        = 246808,
    Fish                             = 246809,
    Vegetables                       = 246810,
    Cotton                           = 246811,
    Oil                              = 246812,
    Ore                              = 246813,
    Coal                             = 246814,
    Stone                            = 246815,
    HeadingMaterialGoods             = 246816,
    Metals                           = 246817,
    Steel                            = 246818,
    Minerals                         = 246819,
    Concrete                         = 246820,
    Machinery                        = 246821,
    Petrochemicals                   = 246822,
    Chemicals                        = 246823,
    Plastics                         = 246824,
    Pharmaceuticals                  = 246825,
    Electronics                      = 246826,
    Vehicles                         = 246827,
    Beverages                        = 246828,
    ConvenienceFood                  = 246829,
    Food                             = 246830,
    Textiles                         = 246831,
    Timber                           = 246832,
    Paper                            = 246833,
    Furniture                        = 246834,
    HeadingImmaterialGoods           = 246835,
    Software                         = 246836,
    Telecom                          = 246837,
    Financial                        = 246838,
    Media                            = 246839,
    Lodging                          = 246840,
    Meals                            = 246841,
    Entertainment                    = 246842,
    Recreation                       = 246843,
    MaxValues                        = 246844,
}

// Define display options.
export enum DisplayOption
{
    Requires                         = 0,
    Produces                         = 1,
    Sells                            = 2,
    Stores                           = 3,
}

// Define color options.
export enum ColorOption
{
    Multiple                         = 0,
    One                              = 1,
}
