// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIFiles.
// Make any needed changes in class CreateUIFiles.


// Define building types.
export enum RLBuildingType
{
    None                             = 246800,
    District                         = 246801,
    DisplayOption                    = 246802,
    SelectDeselect                   = 246803,
    HeadingMaterials                 = 246804,
    Wood                             = 246805,
    Grain                            = 246806,
    Livestock                        = 246807,
    Vegetables                       = 246808,
    Cotton                           = 246809,
    Oil                              = 246810,
    Ore                              = 246811,
    Coal                             = 246812,
    Stone                            = 246813,
    HeadingMaterialGoods             = 246814,
    Metals                           = 246815,
    Steel                            = 246816,
    Minerals                         = 246817,
    Concrete                         = 246818,
    Machinery                        = 246819,
    Petrochemicals                   = 246820,
    Chemicals                        = 246821,
    Plastics                         = 246822,
    Pharmaceuticals                  = 246823,
    Electronics                      = 246824,
    Vehicles                         = 246825,
    Beverages                        = 246826,
    ConvenienceFood                  = 246827,
    Food                             = 246828,
    Textiles                         = 246829,
    Timber                           = 246830,
    Paper                            = 246831,
    Furniture                        = 246832,
    HeadingImmaterialGoods           = 246833,
    Software                         = 246834,
    Telecom                          = 246835,
    Financial                        = 246836,
    Media                            = 246837,
    Lodging                          = 246838,
    Meals                            = 246839,
    Entertainment                    = 246840,
    Recreation                       = 246841,
    MaxValues                        = 246842,
}

// Define display options.
export enum DisplayOption
{
    Requires                         = 0,
    Produces                         = 1,
    Sells                            = 2,
    Stores                           = 3,
}
