// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIFiles.
// Make any needed changes in class CreateUIFiles.

// Define UI translation keys.
export class UITranslationKey
{
    // Mod title and description.
    public static Title                                             : string = "ResourceLocator.Title";
    public static Description                                       : string = "ResourceLocator.Description";

    // Infoview title.
    public static InfoviewTitle                                     : string = "Infoviews.INFOVIEW[ResourceLocator]";

    // Infomode titles.
    public static InfomodeTitleWood                                 : string = "Infoviews.INFOMODE[ResourceLocatorWood]";
    public static InfomodeTitleGrain                                : string = "Infoviews.INFOMODE[ResourceLocatorGrain]";
    public static InfomodeTitleLivestock                            : string = "Infoviews.INFOMODE[ResourceLocatorLivestock]";
    public static InfomodeTitleFish                                 : string = "Infoviews.INFOMODE[ResourceLocatorFish]";
    public static InfomodeTitleVegetables                           : string = "Infoviews.INFOMODE[ResourceLocatorVegetables]";
    public static InfomodeTitleCotton                               : string = "Infoviews.INFOMODE[ResourceLocatorCotton]";
    public static InfomodeTitleOil                                  : string = "Infoviews.INFOMODE[ResourceLocatorOil]";
    public static InfomodeTitleOre                                  : string = "Infoviews.INFOMODE[ResourceLocatorOre]";
    public static InfomodeTitleCoal                                 : string = "Infoviews.INFOMODE[ResourceLocatorCoal]";
    public static InfomodeTitleStone                                : string = "Infoviews.INFOMODE[ResourceLocatorStone]";
    public static InfomodeTitleMetals                               : string = "Infoviews.INFOMODE[ResourceLocatorMetals]";
    public static InfomodeTitleSteel                                : string = "Infoviews.INFOMODE[ResourceLocatorSteel]";
    public static InfomodeTitleMinerals                             : string = "Infoviews.INFOMODE[ResourceLocatorMinerals]";
    public static InfomodeTitleConcrete                             : string = "Infoviews.INFOMODE[ResourceLocatorConcrete]";
    public static InfomodeTitleMachinery                            : string = "Infoviews.INFOMODE[ResourceLocatorMachinery]";
    public static InfomodeTitlePetrochemicals                       : string = "Infoviews.INFOMODE[ResourceLocatorPetrochemicals]";
    public static InfomodeTitleChemicals                            : string = "Infoviews.INFOMODE[ResourceLocatorChemicals]";
    public static InfomodeTitlePlastics                             : string = "Infoviews.INFOMODE[ResourceLocatorPlastics]";
    public static InfomodeTitlePharmaceuticals                      : string = "Infoviews.INFOMODE[ResourceLocatorPharmaceuticals]";
    public static InfomodeTitleElectronics                          : string = "Infoviews.INFOMODE[ResourceLocatorElectronics]";
    public static InfomodeTitleVehicles                             : string = "Infoviews.INFOMODE[ResourceLocatorVehicles]";
    public static InfomodeTitleBeverages                            : string = "Infoviews.INFOMODE[ResourceLocatorBeverages]";
    public static InfomodeTitleConvenienceFood                      : string = "Infoviews.INFOMODE[ResourceLocatorConvenienceFood]";
    public static InfomodeTitleFood                                 : string = "Infoviews.INFOMODE[ResourceLocatorFood]";
    public static InfomodeTitleTextiles                             : string = "Infoviews.INFOMODE[ResourceLocatorTextiles]";
    public static InfomodeTitleTimber                               : string = "Infoviews.INFOMODE[ResourceLocatorTimber]";
    public static InfomodeTitlePaper                                : string = "Infoviews.INFOMODE[ResourceLocatorPaper]";
    public static InfomodeTitleFurniture                            : string = "Infoviews.INFOMODE[ResourceLocatorFurniture]";
    public static InfomodeTitleSoftware                             : string = "Infoviews.INFOMODE[ResourceLocatorSoftware]";
    public static InfomodeTitleTelecom                              : string = "Infoviews.INFOMODE[ResourceLocatorTelecom]";
    public static InfomodeTitleFinancial                            : string = "Infoviews.INFOMODE[ResourceLocatorFinancial]";
    public static InfomodeTitleMedia                                : string = "Infoviews.INFOMODE[ResourceLocatorMedia]";
    public static InfomodeTitleLodging                              : string = "Infoviews.INFOMODE[ResourceLocatorLodging]";
    public static InfomodeTitleMeals                                : string = "Infoviews.INFOMODE[ResourceLocatorMeals]";
    public static InfomodeTitleEntertainment                        : string = "Infoviews.INFOMODE[ResourceLocatorEntertainment]";
    public static InfomodeTitleRecreation                           : string = "Infoviews.INFOMODE[ResourceLocatorRecreation]";

    // Infomode tooltips.
    public static InfomodeTooltipWood                               : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorWood]";
    public static InfomodeTooltipGrain                              : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorGrain]";
    public static InfomodeTooltipLivestock                          : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorLivestock]";
    public static InfomodeTooltipFish                               : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorFish]";
    public static InfomodeTooltipVegetables                         : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorVegetables]";
    public static InfomodeTooltipCotton                             : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorCotton]";
    public static InfomodeTooltipOil                                : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorOil]";
    public static InfomodeTooltipOre                                : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorOre]";
    public static InfomodeTooltipCoal                               : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorCoal]";
    public static InfomodeTooltipStone                              : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorStone]";
    public static InfomodeTooltipMetals                             : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMetals]";
    public static InfomodeTooltipSteel                              : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorSteel]";
    public static InfomodeTooltipMinerals                           : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMinerals]";
    public static InfomodeTooltipConcrete                           : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorConcrete]";
    public static InfomodeTooltipMachinery                          : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMachinery]";
    public static InfomodeTooltipPetrochemicals                     : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorPetrochemicals]";
    public static InfomodeTooltipChemicals                          : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorChemicals]";
    public static InfomodeTooltipPlastics                           : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorPlastics]";
    public static InfomodeTooltipPharmaceuticals                    : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorPharmaceuticals]";
    public static InfomodeTooltipElectronics                        : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorElectronics]";
    public static InfomodeTooltipVehicles                           : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorVehicles]";
    public static InfomodeTooltipBeverages                          : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorBeverages]";
    public static InfomodeTooltipConvenienceFood                    : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorConvenienceFood]";
    public static InfomodeTooltipFood                               : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorFood]";
    public static InfomodeTooltipTextiles                           : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorTextiles]";
    public static InfomodeTooltipTimber                             : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorTimber]";
    public static InfomodeTooltipPaper                              : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorPaper]";
    public static InfomodeTooltipFurniture                          : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorFurniture]";
    public static InfomodeTooltipSoftware                           : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorSoftware]";
    public static InfomodeTooltipTelecom                            : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorTelecom]";
    public static InfomodeTooltipFinancial                          : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorFinancial]";
    public static InfomodeTooltipMedia                              : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMedia]";
    public static InfomodeTooltipLodging                            : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorLodging]";
    public static InfomodeTooltipMeals                              : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMeals]";
    public static InfomodeTooltipEntertainment                      : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorEntertainment]";
    public static InfomodeTooltipRecreation                         : string = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorRecreation]";

    // District selector text.
    public static EntireCity                                        : string = "ResourceLocator.EntireCity";
    public static DistrictSelectorTooltip                           : string = "ResourceLocator.DistrictSelectorTooltip";

    // Display option text.
    public static DisplayOptionRequires                             : string = "ResourceLocator.DisplayOptionRequires";
    public static DisplayOptionProduces                             : string = "ResourceLocator.DisplayOptionProduces";
    public static DisplayOptionSells                                : string = "ResourceLocator.DisplayOptionSells";
    public static DisplayOptionStores                               : string = "ResourceLocator.DisplayOptionStores";
    public static DisplayOptionTooltip                              : string = "ResourceLocator.DisplayOptionTooltip";

    // Select/deselect text.
    public static SelectAll                                         : string = "ResourceLocator.SelectAll";
    public static DeselectAll                                       : string = "ResourceLocator.DeselectAll";
    public static SelectDeselectTooltip                             : string = "ResourceLocator.SelectDeselectTooltip";

    // Resource category text.
    public static Materials                                         : string = "ResourceLocator.Materials";
    public static MaterialGoods                                     : string = "ResourceLocator.MaterialGoods";
    public static ImmaterialGoods                                   : string = "ResourceLocator.ImmaterialGoods";

    // Unit of measure text.
    public static UnitOfMeasurePrefixKilo                           : string = "ResourceLocator.UnitOfMeasurePrefixKilo";
}
