// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIFiles.
// Make any needed changes in class CreateUIFiles.

namespace ResourceLocator
{
    // Define UI translation keys.
    public class UITranslationKey
    {
        // Mod title and description.
        public const string Title                                              = "ResourceLocator.Title";
        public const string Description                                        = "ResourceLocator.Description";

        // Infoview title.
        public const string InfoviewTitle                                      = "Infoviews.INFOVIEW[ResourceLocator]";

        // Infomode titles.
        public const string InfomodeTitleWood                                  = "Infoviews.INFOMODE[ResourceLocatorWood]";
        public const string InfomodeTitleGrain                                 = "Infoviews.INFOMODE[ResourceLocatorGrain]";
        public const string InfomodeTitleLivestock                             = "Infoviews.INFOMODE[ResourceLocatorLivestock]";
        public const string InfomodeTitleFish                                  = "Infoviews.INFOMODE[ResourceLocatorFish]";
        public const string InfomodeTitleVegetables                            = "Infoviews.INFOMODE[ResourceLocatorVegetables]";
        public const string InfomodeTitleCotton                                = "Infoviews.INFOMODE[ResourceLocatorCotton]";
        public const string InfomodeTitleOil                                   = "Infoviews.INFOMODE[ResourceLocatorOil]";
        public const string InfomodeTitleOre                                   = "Infoviews.INFOMODE[ResourceLocatorOre]";
        public const string InfomodeTitleCoal                                  = "Infoviews.INFOMODE[ResourceLocatorCoal]";
        public const string InfomodeTitleStone                                 = "Infoviews.INFOMODE[ResourceLocatorStone]";
        public const string InfomodeTitleMetals                                = "Infoviews.INFOMODE[ResourceLocatorMetals]";
        public const string InfomodeTitleSteel                                 = "Infoviews.INFOMODE[ResourceLocatorSteel]";
        public const string InfomodeTitleMinerals                              = "Infoviews.INFOMODE[ResourceLocatorMinerals]";
        public const string InfomodeTitleConcrete                              = "Infoviews.INFOMODE[ResourceLocatorConcrete]";
        public const string InfomodeTitleMachinery                             = "Infoviews.INFOMODE[ResourceLocatorMachinery]";
        public const string InfomodeTitlePetrochemicals                        = "Infoviews.INFOMODE[ResourceLocatorPetrochemicals]";
        public const string InfomodeTitleChemicals                             = "Infoviews.INFOMODE[ResourceLocatorChemicals]";
        public const string InfomodeTitlePlastics                              = "Infoviews.INFOMODE[ResourceLocatorPlastics]";
        public const string InfomodeTitlePharmaceuticals                       = "Infoviews.INFOMODE[ResourceLocatorPharmaceuticals]";
        public const string InfomodeTitleElectronics                           = "Infoviews.INFOMODE[ResourceLocatorElectronics]";
        public const string InfomodeTitleVehicles                              = "Infoviews.INFOMODE[ResourceLocatorVehicles]";
        public const string InfomodeTitleBeverages                             = "Infoviews.INFOMODE[ResourceLocatorBeverages]";
        public const string InfomodeTitleConvenienceFood                       = "Infoviews.INFOMODE[ResourceLocatorConvenienceFood]";
        public const string InfomodeTitleFood                                  = "Infoviews.INFOMODE[ResourceLocatorFood]";
        public const string InfomodeTitleTextiles                              = "Infoviews.INFOMODE[ResourceLocatorTextiles]";
        public const string InfomodeTitleTimber                                = "Infoviews.INFOMODE[ResourceLocatorTimber]";
        public const string InfomodeTitlePaper                                 = "Infoviews.INFOMODE[ResourceLocatorPaper]";
        public const string InfomodeTitleFurniture                             = "Infoviews.INFOMODE[ResourceLocatorFurniture]";
        public const string InfomodeTitleSoftware                              = "Infoviews.INFOMODE[ResourceLocatorSoftware]";
        public const string InfomodeTitleTelecom                               = "Infoviews.INFOMODE[ResourceLocatorTelecom]";
        public const string InfomodeTitleFinancial                             = "Infoviews.INFOMODE[ResourceLocatorFinancial]";
        public const string InfomodeTitleMedia                                 = "Infoviews.INFOMODE[ResourceLocatorMedia]";
        public const string InfomodeTitleLodging                               = "Infoviews.INFOMODE[ResourceLocatorLodging]";
        public const string InfomodeTitleMeals                                 = "Infoviews.INFOMODE[ResourceLocatorMeals]";
        public const string InfomodeTitleEntertainment                         = "Infoviews.INFOMODE[ResourceLocatorEntertainment]";
        public const string InfomodeTitleRecreation                            = "Infoviews.INFOMODE[ResourceLocatorRecreation]";

        // Infomode tooltips.
        public const string InfomodeTooltipWood                                = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorWood]";
        public const string InfomodeTooltipGrain                               = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorGrain]";
        public const string InfomodeTooltipLivestock                           = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorLivestock]";
        public const string InfomodeTooltipFish                                = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorFish]";
        public const string InfomodeTooltipVegetables                          = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorVegetables]";
        public const string InfomodeTooltipCotton                              = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorCotton]";
        public const string InfomodeTooltipOil                                 = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorOil]";
        public const string InfomodeTooltipOre                                 = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorOre]";
        public const string InfomodeTooltipCoal                                = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorCoal]";
        public const string InfomodeTooltipStone                               = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorStone]";
        public const string InfomodeTooltipMetals                              = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMetals]";
        public const string InfomodeTooltipSteel                               = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorSteel]";
        public const string InfomodeTooltipMinerals                            = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMinerals]";
        public const string InfomodeTooltipConcrete                            = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorConcrete]";
        public const string InfomodeTooltipMachinery                           = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMachinery]";
        public const string InfomodeTooltipPetrochemicals                      = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorPetrochemicals]";
        public const string InfomodeTooltipChemicals                           = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorChemicals]";
        public const string InfomodeTooltipPlastics                            = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorPlastics]";
        public const string InfomodeTooltipPharmaceuticals                     = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorPharmaceuticals]";
        public const string InfomodeTooltipElectronics                         = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorElectronics]";
        public const string InfomodeTooltipVehicles                            = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorVehicles]";
        public const string InfomodeTooltipBeverages                           = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorBeverages]";
        public const string InfomodeTooltipConvenienceFood                     = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorConvenienceFood]";
        public const string InfomodeTooltipFood                                = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorFood]";
        public const string InfomodeTooltipTextiles                            = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorTextiles]";
        public const string InfomodeTooltipTimber                              = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorTimber]";
        public const string InfomodeTooltipPaper                               = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorPaper]";
        public const string InfomodeTooltipFurniture                           = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorFurniture]";
        public const string InfomodeTooltipSoftware                            = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorSoftware]";
        public const string InfomodeTooltipTelecom                             = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorTelecom]";
        public const string InfomodeTooltipFinancial                           = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorFinancial]";
        public const string InfomodeTooltipMedia                               = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMedia]";
        public const string InfomodeTooltipLodging                             = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorLodging]";
        public const string InfomodeTooltipMeals                               = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorMeals]";
        public const string InfomodeTooltipEntertainment                       = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorEntertainment]";
        public const string InfomodeTooltipRecreation                          = "Infoviews.INFOMODE_TOOLTIP[ResourceLocatorRecreation]";

        // District selector text.
        public const string EntireCity                                         = "ResourceLocator.EntireCity";
        public const string DistrictSelectorTooltip                            = "ResourceLocator.DistrictSelectorTooltip";

        // Display option text.
        public const string DisplayOptionRequires                              = "ResourceLocator.DisplayOptionRequires";
        public const string DisplayOptionProduces                              = "ResourceLocator.DisplayOptionProduces";
        public const string DisplayOptionSells                                 = "ResourceLocator.DisplayOptionSells";
        public const string DisplayOptionStores                                = "ResourceLocator.DisplayOptionStores";
        public const string DisplayOptionTooltip                               = "ResourceLocator.DisplayOptionTooltip";

        // Select/deselect text.
        public const string SelectAll                                          = "ResourceLocator.SelectAll";
        public const string DeselectAll                                        = "ResourceLocator.DeselectAll";
        public const string SelectDeselectTooltip                              = "ResourceLocator.SelectDeselectTooltip";

        // Resource category text.
        public const string Materials                                          = "ResourceLocator.Materials";
        public const string MaterialGoods                                      = "ResourceLocator.MaterialGoods";
        public const string ImmaterialGoods                                    = "ResourceLocator.ImmaterialGoods";

        // Unit of measure text.
        public const string UnitOfMeasurePrefixKilo                            = "ResourceLocator.UnitOfMeasurePrefixKilo";

        // Settings.
        public const string SettingTitle                                       = "Options.SECTION[ResourceLocator.ResourceLocator.Mod]";
        public const string SettingGroupInclude                                = "Options.GROUP[ResourceLocator.ResourceLocator.Mod.Include]";
        public const string SettingIncludeGeneralDescription                   = "Options.OPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeGeneralDescription]";
        public const string SettingIncludeRecyclingCenterLabel                 = "Options.OPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeRecyclingCenter]";
        public const string SettingIncludeRecyclingCenterDesc                  = "Options.OPTION_DESCRIPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeRecyclingCenter]";
        public const string SettingIncludeCoalPowerPlantLabel                  = "Options.OPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeCoalPowerPlant]";
        public const string SettingIncludeCoalPowerPlantDesc                   = "Options.OPTION_DESCRIPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeCoalPowerPlant]";
        public const string SettingIncludeGasPowerPlantLabel                   = "Options.OPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeGasPowerPlant]";
        public const string SettingIncludeGasPowerPlantDesc                    = "Options.OPTION_DESCRIPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeGasPowerPlant]";
        public const string SettingIncludeMedicalFacilityLabel                 = "Options.OPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeMedicalFacility]";
        public const string SettingIncludeMedicalFacilityDesc                  = "Options.OPTION_DESCRIPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeMedicalFacility]";
        public const string SettingIncludeEmeregencyShelterLabel               = "Options.OPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeEmeregencyShelter]";
        public const string SettingIncludeEmeregencyShelterDesc                = "Options.OPTION_DESCRIPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeEmeregencyShelter]";
        public const string SettingIncludeCargoStationLabel                    = "Options.OPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeCargoStation]";
        public const string SettingIncludeCargoStationDesc                     = "Options.OPTION_DESCRIPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.IncludeCargoStation]";
        public const string SettingGroupAbout                                  = "Options.GROUP[ResourceLocator.ResourceLocator.Mod.About]";
        public const string SettingModVersionLabel                             = "Options.OPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.ModVersion]";
        public const string SettingModVersionDesc                              = "Options.OPTION_DESCRIPTION[ResourceLocator.ResourceLocator.Mod.ModSettings.ModVersion]";
    }
}
