// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace ResourceLocator
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "ResourceLocator";
        public const string Version     = "1.4.0";
        public const string Title       = "Resource Locator";
        public const string Description = "New info view to locate buildings where resources are required, produced, sold, and stored.";
    }
}
